
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
import Objects.*;
import Classes.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserCapas extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserCapas() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserCapas(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCapas(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\003\013\000\002\003\013\000\002\004\011" +
    "\000\002\004\004\000\002\004\003\000\002\005\003\000" +
    "\002\005\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\042\000\010\003\006\004\004\005\010\001\002\000" +
    "\004\007\035\001\002\000\004\002\000\001\002\000\004" +
    "\002\uffff\001\002\000\004\002\034\001\002\000\004\007" +
    "\011\001\002\000\004\005\012\001\002\000\004\011\013" +
    "\001\002\000\004\005\014\001\002\000\004\011\015\001" +
    "\002\000\004\006\016\001\002\000\004\012\017\001\002" +
    "\000\010\003\021\005\023\010\020\001\002\000\010\002" +
    "\ufff8\004\004\005\010\001\002\000\004\002\ufffa\001\002" +
    "\000\004\002\ufffd\001\002\000\004\011\024\001\002\000" +
    "\004\005\025\001\002\000\004\011\026\001\002\000\004" +
    "\006\027\001\002\000\004\012\030\001\002\000\010\003" +
    "\021\005\023\010\020\001\002\000\004\002\ufffc\001\002" +
    "\000\004\002\ufffb\001\002\000\004\002\ufff9\001\002\000" +
    "\004\002\001\001\002\000\004\005\036\001\002\000\004" +
    "\011\037\001\002\000\004\005\040\001\002\000\004\011" +
    "\041\001\002\000\004\006\042\001\002\000\004\012\043" +
    "\001\002\000\010\003\021\005\023\010\020\001\002\000" +
    "\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\042\000\006\002\006\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\021\001\001\000\006\003\032\005" +
    "\031\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\004\030\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\043\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCapas$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCapas$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCapas$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    //Listas
    //private ArrayList<Capa> capasList= new ArrayList<Capa>();
    MatrizDispersa capaGenerada = new MatrizDispersa();
    String idActual="EE";
	public ParserCapas(LexicoCapas lex) {
		super(lex);
	}
	@Override
        public void syntax_error(Symbol st) {
            //Reporte el error
        	Token token = (Token) st.value;
            report_error("Error Sintactico con el  Token:"+ token.getLexeme()+" este no pertenece a la estructura - linea: "+token.getLine()+" - columna: "+token.getColumn() + "\n",null);
        }
    public void setIdActual(String id){
        this.idActual=id;
    }
    


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserCapas$actions {
  private final ParserCapas parser;

  /** Constructor */
  CUP$ParserCapas$actions(ParserCapas parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserCapas$do_action_part00000000(
    int                        CUP$ParserCapas$act_num,
    java_cup.runtime.lr_parser CUP$ParserCapas$parser,
    java.util.Stack            CUP$ParserCapas$stack,
    int                        CUP$ParserCapas$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCapas$result;

      /* select the action based on the action number */
      switch (CUP$ParserCapas$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)).value;
		RESULT = start_val;
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCapas$parser.done_parsing();
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= CREARCAPA 
            {
              Object RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= error 
            {
              Object RESULT =null;
		System.out.println("Error en expresion");
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // CREARCAPA ::= ID LLAVEA ENTERO COMA ENTERO COMA HEXADECIMAL PUNTOCOMA SIGUIENTE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-8)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-8)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-8)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-6)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-6)).right;
		Token x = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-6)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-4)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-4)).right;
		Token y = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-4)).value;
		int colorleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-2)).left;
		int colorright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-2)).right;
		Token color = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-2)).value;
		setIdActual(id.getLexeme());
   capaGenerada.insertar(Integer.parseInt(x.getLexeme()), Integer.parseInt(y.getLexeme()), color.getLexeme()); 
   claseMain.arbolABB.insertar(idActual,capaGenerada);
   capaGenerada = new MatrizDispersa();
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("CREARCAPA",1, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-8)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // CREARCAPA ::= ENTERO LLAVEA ENTERO COMA ENTERO COMA HEXADECIMAL PUNTOCOMA SIGUIENTE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-8)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-8)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-8)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-6)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-6)).right;
		Token x = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-6)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-4)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-4)).right;
		Token y = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-4)).value;
		int colorleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-2)).left;
		int colorright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-2)).right;
		Token color = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-2)).value;
		setIdActual(id.getLexeme());
   capaGenerada.insertar(Integer.parseInt(x.getLexeme()), Integer.parseInt(y.getLexeme()), color.getLexeme()); 
   claseMain.arbolABB.insertar(idActual,capaGenerada);
   capaGenerada = new MatrizDispersa();
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("CREARCAPA",1, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-8)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // SIGUIENTE ::= ENTERO COMA ENTERO COMA HEXADECIMAL PUNTOCOMA SIGUIENTE 
            {
              Object RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-6)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-6)).right;
		Token x = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-6)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-4)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-4)).right;
		Token y = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-4)).value;
		int colorleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-2)).left;
		int colorright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-2)).right;
		Token color = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-2)).value;
		capaGenerada.insertar(Integer.parseInt(x.getLexeme()), Integer.parseInt(y.getLexeme()), color.getLexeme()); 
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("SIGUIENTE",2, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SIGUIENTE ::= LLAVEB FINOINICIO 
            {
              Object RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("SIGUIENTE",2, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SIGUIENTE ::= error 
            {
              Object RESULT =null;
		System.out.println("Error en expresion");
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("SIGUIENTE",2, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // FINOINICIO ::= CREARCAPA 
            {
              Object RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("FINOINICIO",3, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // FINOINICIO ::= 
            {
              Object RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("FINOINICIO",3, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserCapas$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserCapas$do_action(
    int                        CUP$ParserCapas$act_num,
    java_cup.runtime.lr_parser CUP$ParserCapas$parser,
    java.util.Stack            CUP$ParserCapas$stack,
    int                        CUP$ParserCapas$top)
    throws java.lang.Exception
    {
              return CUP$ParserCapas$do_action_part00000000(
                               CUP$ParserCapas$act_num,
                               CUP$ParserCapas$parser,
                               CUP$ParserCapas$stack,
                               CUP$ParserCapas$top);
    }
}

}
