
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
import Objects.*;
import Classes.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserUsuarios extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym3.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserUsuarios() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserUsuarios(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserUsuarios(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\003\005\000\002\003\005\000\002\004\005" +
    "\000\002\004\005\000\002\004\003\000\002\005\003\000" +
    "\002\005\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\010\003\005\004\004\005\010\001\002\000" +
    "\004\010\023\001\002\000\004\002\uffff\001\002\000\004" +
    "\002\000\001\002\000\004\002\022\001\002\000\004\010" +
    "\011\001\002\000\006\003\012\005\014\001\002\000\004" +
    "\002\ufffa\001\002\000\004\002\ufffd\001\002\000\006\006" +
    "\016\007\015\001\002\000\006\003\012\005\014\001\002" +
    "\000\010\002\ufff8\004\004\005\010\001\002\000\004\002" +
    "\ufffc\001\002\000\004\002\ufff9\001\002\000\004\002\ufffb" +
    "\001\002\000\004\002\001\001\002\000\006\003\012\005" +
    "\014\001\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\006\002\006\003\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\012\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\004\020" +
    "\001\001\000\006\003\017\005\016\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\023\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserUsuarios$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserUsuarios$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserUsuarios$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    //Metodos
    Usuario usuarioGenerado=new Usuario("");
	public ParserUsuarios(LexicoUsuarios lex) {
		super(lex);
	}
	@Override
        public void syntax_error(Symbol st) {
            //Reporte el error
        	Token token = (Token) st.value;
            report_error("Error Sintactico con el  Token:"+ token.getLexeme()+" este no pertenece a la estructura - linea: "+token.getLine()+" - columna: "+token.getColumn() + "\n",null);
        }
    


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserUsuarios$actions {
  private final ParserUsuarios parser;

  /** Constructor */
  CUP$ParserUsuarios$actions(ParserUsuarios parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserUsuarios$do_action_part00000000(
    int                        CUP$ParserUsuarios$act_num,
    java_cup.runtime.lr_parser CUP$ParserUsuarios$parser,
    java.util.Stack            CUP$ParserUsuarios$stack,
    int                        CUP$ParserUsuarios$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserUsuarios$result;

      /* select the action based on the action number */
      switch (CUP$ParserUsuarios$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-1)).value;
		RESULT = start_val;
              CUP$ParserUsuarios$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-1)), ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserUsuarios$parser.done_parsing();
          return CUP$ParserUsuarios$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= CREARUSUARIO 
            {
              Object RESULT =null;

              CUP$ParserUsuarios$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), RESULT);
            }
          return CUP$ParserUsuarios$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= error 
            {
              Object RESULT =null;
		System.out.println("Error en expresion");
              CUP$ParserUsuarios$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), RESULT);
            }
          return CUP$ParserUsuarios$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // CREARUSUARIO ::= ID DOSPUNTOS SIGUIENTE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).value;
		
usuarioGenerado.setUsuario(id.getLexeme());
   claseMain.arbolAVL.insertar2(usuarioGenerado);
   usuarioGenerado=new Usuario("");
              CUP$ParserUsuarios$result = parser.getSymbolFactory().newSymbol("CREARUSUARIO",1, ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)), ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), RESULT);
            }
          return CUP$ParserUsuarios$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // CREARUSUARIO ::= ENTERO DOSPUNTOS SIGUIENTE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).value;
		
   usuarioGenerado.setUsuario(id.getLexeme());
   claseMain.arbolAVL.insertar2(usuarioGenerado);
   usuarioGenerado=new Usuario("");
              CUP$ParserUsuarios$result = parser.getSymbolFactory().newSymbol("CREARUSUARIO",1, ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)), ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), RESULT);
            }
          return CUP$ParserUsuarios$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // SIGUIENTE ::= ENTERO PUNTOCOMA FINOINICIO 
            {
              Object RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).right;
		Token num = (Token)((java_cup.runtime.Symbol) CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).value;
		
NodoListaDoble nodo=claseMain.listaImagenes.buscarImagen(num.getLexeme());
   Imagen encontrada=nodo.getImagen();
   usuarioGenerado.insertarImagenCola(encontrada);
              CUP$ParserUsuarios$result = parser.getSymbolFactory().newSymbol("SIGUIENTE",2, ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)), ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), RESULT);
            }
          return CUP$ParserUsuarios$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SIGUIENTE ::= ENTERO COMA SIGUIENTE 
            {
              Object RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).right;
		Token num = (Token)((java_cup.runtime.Symbol) CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)).value;
		 
NodoListaDoble nodo=claseMain.listaImagenes.buscarImagen(num.getLexeme());
   Imagen encontrada=nodo.getImagen();
   usuarioGenerado.insertarImagenCola(encontrada);
              CUP$ParserUsuarios$result = parser.getSymbolFactory().newSymbol("SIGUIENTE",2, ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.elementAt(CUP$ParserUsuarios$top-2)), ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), RESULT);
            }
          return CUP$ParserUsuarios$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SIGUIENTE ::= error 
            {
              Object RESULT =null;
		System.out.println("Error en expresion");
              CUP$ParserUsuarios$result = parser.getSymbolFactory().newSymbol("SIGUIENTE",2, ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), RESULT);
            }
          return CUP$ParserUsuarios$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // FINOINICIO ::= CREARUSUARIO 
            {
              Object RESULT =null;

              CUP$ParserUsuarios$result = parser.getSymbolFactory().newSymbol("FINOINICIO",3, ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), RESULT);
            }
          return CUP$ParserUsuarios$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // FINOINICIO ::= 
            {
              Object RESULT =null;

              CUP$ParserUsuarios$result = parser.getSymbolFactory().newSymbol("FINOINICIO",3, ((java_cup.runtime.Symbol)CUP$ParserUsuarios$stack.peek()), RESULT);
            }
          return CUP$ParserUsuarios$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserUsuarios$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserUsuarios$do_action(
    int                        CUP$ParserUsuarios$act_num,
    java_cup.runtime.lr_parser CUP$ParserUsuarios$parser,
    java.util.Stack            CUP$ParserUsuarios$stack,
    int                        CUP$ParserUsuarios$top)
    throws java.lang.Exception
    {
              return CUP$ParserUsuarios$do_action_part00000000(
                               CUP$ParserUsuarios$act_num,
                               CUP$ParserUsuarios$parser,
                               CUP$ParserUsuarios$stack,
                               CUP$ParserUsuarios$top);
    }
}

}
