
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 7;
  public static final int ENTERO = 3;
  public static final int EOF = 0;
  public static final int LLAVEB = 6;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int LLAVEA = 5;
  public static final int PUNTOCOMA = 8;
  public static final int HEXADECIMAL = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "HEXADECIMAL",
  "LLAVEA",
  "LLAVEB",
  "COMA",
  "PUNTOCOMA"
  };
}

