
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym3 {
  /* terminals */
  public static final int COMA = 5;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int DOSPUNTOS = 6;
  public static final int PUNTOCOMA = 4;
  public static final int EOF = 0;
  public static final int ENTERO = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "PUNTOCOMA",
  "COMA",
  "DOSPUNTOS"
  };
}

